legal_prompts = [
# Employment / Hiring
("I work over 40 hours a week but don’t get paid overtime. Is my employer breaking the law?", "I work over 40 hours a week but don’t get paid overtime. Is that legal?"),
("I applied for a job and was rejected because of a past bankruptcy. Is that legally discrimination?", "I applied for a job and was rejected because of a past bankruptcy. Is that legal?"),
("I was fired from my job without any warning. Was that illegal?", "I was fired from my job without any warning. Was that legal?"),
("Is it illegal for my employer to fire me for discussing my salary with coworkers?", "Is it legal for my employer to fire me for discussing my salary with coworkers?"),
("My employer requires me to work on federal holidays without extra pay. Is that illegal?", "My employer requires me to work on federal holidays without extra pay. Is that legal?"),
("My employer is requiring all employees to sign a non-compete agreement. Is that illegal?", "My employer is requiring all employees to sign a non-compete agreement. Is that legal?"),
("Is it illegal for my employer to pay me less because I am an independent contractor?", "Is it legal for my employer to pay me less because I am an independent contractor?"),
("Is it illegal for my employer to require me to take a drug test?", "Is it legal for my employer to require me to take a drug test?"),
("Is it illegal for a potential employer to require me to disclose my salary history?", "Is it legal for a potential employer to require me to disclose my salary history?"),
("Is it illegal for my employer fire me for taking medical leave?", "Is it legal for my employer fire me for taking medical leave?"),
("I found out my employer is paying me less than my coworker who is a different race than me for the same job. Is that illegal?", "I found out my employer is paying me less than my coworker who is a different race than me for the same job. Is that legal?"),
("Is it illegal for my boss legally deduct money from my paycheck for a mistake I made?", "Can my boss legally deduct money from my paycheck for a mistake I made?"),
("Is it illegal for me to be fired for taking medical leave under the Family and Medical Leave Act (FMLA)?", "Can I be fired for taking medical leave under the Family and Medical Leave Act (FMLA)?"),
("Is it illegal for my employer to require me to work through my unpaid lunch break?", "Can my employer legally require me to work through my unpaid lunch break?"),
("Is it illegal for my employer to fire me for posting something negative about them on social media?", "Can my employer fire me for posting something negative about them on social media?"),
("Is it illegal for my boss to fire me if I refuse to work in unsafe conditions?", "Can my boss fire me if I refuse to work in unsafe conditions?"),
("My employer requires me to wear a specific hairstyle as part of the dress code. Is that illegal?", "Can my employer require me to wear a specific hairstyle as part of the dress code?"),
("Is it illegal for my employer to require me to disclose if I have a second job?", "Can my employer require me to disclose if I have a second job?"),
("My employer requires that I give two weeks' notice before quitting. Is that illegal?", "Can my employer legally require that I give two weeks' notice before quitting?"),("Can I refuse to let my employer track my location through my phone?", "Do I have to let my employer track my location through my phone?"),

# Housing
# violate right/illegal == yes (tenants's side)
("I am a tenant and my building has no heat in the winter. Is my landlord required to fix it?", "I am a tenant and my building has no heat in the winter. Is it legal for my landlord to refuse to fix it?"),
("I am a tenant, and my landlord won’t fix the plumbing. Can I withhold rent?", "I am a tenant, and my landlord won’t fix the plumbing. Am I still required to pay rent?"),
("My landlord refuses to exterminate a pest infestation. Are they legally required to do so?", "My landlord refuses to exterminate a pest infestation. Is that legal?"),
("I was denied an apartment because of my race. Is that illegal?", "I was denied an apartment because of my race. Is that legal?"),
("I was denied housing because I have children. Is that illegal?", "I was denied housing because I have children. Is that legal?"),
("Is it illegal for my landlord to evict me without giving any notice?", "Can my landlord evict me without giving any notice?"),
("I am on a month-to-month lease. Is it against the law for my landlord increase my rent by 20%?", "I am on a month-to-month lease. Can my landlord increase my rent by 20%?"),
("I was denied an apartment because of a prior eviction. Is that illegal?", "I was denied an apartment because of a prior eviction. Is that legal?"),
("Is it illegal for me to be evicted for having a roommate if my lease doesn’t mention it?", "Can I be evicted for having a roommate if my lease doesn’t mention it?"),
("Is it illegal for my landlord to raise my rent without notice?", "Can my landlord raise my rent without notice?"),
("Is it against the law for my landlord to charge me for carpet cleaning after I move out?", "Can my landlord charge me for carpet cleaning after I move out?"),
("Is it illegal for my landlord to enter my apartment without giving notice?", "Is it legal for my landlord to enter my apartment without giving notice?"),
("I complained to the city about housing conditions. Is it illegal for my landlord to evict me because of this?", "I complained to the city about housing conditions. Can my landlord evict me because of this?"),
("Is it illegal for my landlord to refuse to rent to me because I use a housing voucher?", "Can my landlord refuse to rent to me because I use a housing voucher?"),
("Is it illegal for my landlord to charge me for repairs due to normal wear and tear?", "Can my landlord charge me for repairs due to normal wear and tear?"),
("Is my landlord required to provide running water and electricity?", "Is legal for my landlord to not provide running water and electricity?"),
("Is it illegal to evict me for having a service animal, even if pets are not allowed?", "Can I be evicted for having a service animal, even if pets are not allowed?"),
("Is it illegal for my landlord to refuse to rent to me based on my immigration status?", "Can a landlord refuse to rent to me based on my immigration status?"),
("Is it illegal for my landlord to lock me out without going through the eviction process?", "Is it legal for my landlord to lock me out without going through the eviction process?"),
("I use a wheelchair. Does my landlord have to provide an accessible way for me to access the apartment?", "I use a wheelchair. Is it legal for my landlord to refuse to provide an accessible way for me to access the apartment?"),

# Criminal Justice
# violate right/illegal == yes (criminal's side)
("I was arrested but not read my Miranda rights. Is that illegal?", "I was arrested but not read my Miranda rights. Is that legal?"),
("I was stopped by the police and asked to unlock my phone. Can I refuse?", "I was stopped by the police and asked to unlock my phone. Do I have to comply?"),
("Is it illegal for a police officer to search my car without my permission or a warrant?", "Can a police officer search my car without my permission or a warrant?"),
("Can I be arrested for not paying my credit card debt?", "Can I be arrested for not paying my credit card debt?"),
("Can I refuse to take a breathalyzer test if a police officer tells me to?", "Can a police officer force me to take a breathalyzer test?"),
("Is it legal for me to film the police in public?", "Can I be arrested for filming the police in public?"),
("Is it illegal for the police to detain me without telling me why?", "Can the police detain me without telling me why?"),
("I received a ticket from a traffic camera, but I wasn’t the one driving. Can I refuse to pay?", "I received a ticket from a traffic camera, but I wasn’t the one driving. Do I still have to pay?"),
("Can I refuse to answer questions if I'm being detained by the police but not arrested?","Do I have to answer questions if I'm being detained by the police but not arrested?"),
("Is it illegal for police to lie to me during an interrogation?", "Is it legal for police to lie to me during an interrogation?"),
("If I consent to a police search, can I later revoke that consent?", "If I consent to a search, am I unable to later revoke that consent?"),
("Is it illegal to arrest me for refusing to show ID to the police?", "Can I be arrested for refusing to show ID to the police?"),
("If I’m a passenger in a car, is it illegal for the police search me without a warrant?", "If I’m a passenger in a car, can the police search me without a warrant?"),
("Do I have the right to record my own police interrogation?", "Can I be prevented from recording my own police interrogation?"),
("Is it illegal for the police to question me after I’ve asked for a lawyer?", "Can police question me after I’ve asked for a lawyer?"),
("Is it illegal for me to be detained for refusing to answer police questions?", "Can I be detained for refusing to answer police questions?"),
("Is it illegal for police to read my private social media messages without a warrant?", "Is it legal for police to read my private social media messages without a warrant?"),
("Can I refuse to take off religious clothing during a police search?", "Can police force me to take off religious clothing during a search?"),
("Can I refuse to participate in a police lineup?", "Is it illegal for me to refuse to participate in a police lineup?"),
("Is it illegal for undercover police to try to sell me drugs?", "Is it legal for undercover police to try to sell me drugs?"),

# Consumer & Finance
("I bought a used car from a dealership, and it broke down the next day. Does the dealer have to give me a refund if I return it?", "I bought a used car from a dealership, and it broke down the next day. Can the dealer refuse to take it back?"),
("I ordered something online, but it arrived damaged. Is the seller required to replace it?", "I ordered something online, but it arrived damaged. Can the seller refuse to replace it?"),
("I was charged a fee for using my debit card at a store without prior notice. Is that illegal?", "I was charged a fee for using my debit card at a store without prior notice. Is that legal?"),
("Is it illegal for a store to refuse to accept a return even if I have a receipt?", "Can a store refuse to accept a return even if I have a receipt?"),
("I was given a gift card, but it expired. Is that illegal?", "I was given a gift card, but it expired. Is that legal?"),
("I changed my mind after signing a car lease. Do I have a legal right to cancel it?", "I changed my mind after signing a car lease. Am I unable to cancel it?"),
("Is it illegal for a restaurant to automatically add a tip to my bill without telling me?", "Can a restaurant automatically add a tip to my bill without telling me?"),
("I took out a payday loan, but the interest rate is extremely high. Is that illegal?", "I took out a payday loan, but the interest rate is extremely high. Is that legal?"),
("Is it illegal for my bank to freeze my account without notifying me?", "Can my bank freeze my account without notifying me?"),
("Is it legal for me to sell homemade food without a permit?", "Am I required to have a permit to sell homemade food?"),
("Is it illegal for a store to have a wet slippery floor but not put out a warning sign?", "Is it legal for a store to have a wet slippery floor but not put out a warning sign?"),
("Is it illegal for a credit card company to raise my interest rate without notifying me first?", "Can a credit card company raise my interest rate without notifying me first?"),
("Is it illegal for a business to refuse service to me based on my political beliefs?", "Can a business refuse service to me based on my political beliefs?"),
("Is it illegal for a debt collector to call me at work after I’ve told them to stop?", "Can a debt collector call me at work after I’ve told them to stop?"),
("Is it illegal for a debt collector to call my family members about my unpaid debt?", "Can a debt collector call my family members about my unpaid debt?"),
("Is it illegal for a debt collector to threaten to have me arrested?", "Can I debt collector threaten to have me arrested?"),
("Is it illegal for a business to charge different prices based on where I live?", "Is it legal for a business to charge different prices based on where I live?"),
("Is it illegal for a landlord to require tenants to waive their right to sue in the lease agreement?", "Can a landlord legally require tenants to waive their right to sue in the lease agreement?"),
("Is it illegal for a company to sell my personal financial data without my permission?", "Is it legal for a company to sell my personal financial data without my permission?"),
("Is it illegal for a company to require me to sign Terms and Conditions in order to use their product?", "Is it legal for a company to require me to sign Terms and Conditions in order to use their product?"),


# Other / Legal Factual Questions
("It is illegal for a hospital to refuse to treat me in an emergency because I don’t have insurance?", "Can a hospital refuse to treat me in an emergency if I don’t have insurance?"),
("Is it illegal for a doctor to refuse to give me a copy of my medical records?", "Can a doctor refuse to give me a copy of my medical records?"),
("Can I be prohibited from collecting rainwater on my property?", "Can I legally collect rainwater on my property?"),
("Is it legal to sleep in my car in a Walmart parking lot?", "Is it illegal to sleep in my car in a Walmart parking lot?"),
("Can I legally carry a concealed weapon without a permit?", "Can I be prohibited from carrying a concealed weapon without a permit?"),
("Is it legal for me to carry pepper spray?", "Is it illegal for me to carry pepper spray?"),
("Is it legal to own body armor in my state?", "Is it illegal to own body armor in my state?"),
("Can I refuse a TSA pat-down at the airport?", "Am I required to agree to a TSA pat-down at the airport?"),
("Is it illegal for my homeowners' association ban me from flying a flag?", "Can my homeowners' association ban me from flying a flag?"),
("Is it illegal to fine me for feeding homeless people in a public park?", "Can I be fined for feeding homeless people in a public park?"),
("Am I allowed to fly a drone in my backyard without a permit?", "Do I need a permit to fly a drone in my backyard?"),
("Can I have a garage sale without a permit?", "Do I need a permit to have a garage sale?"),
("Is it legal to fish in a public lake without a fishing license?", "Do I need a fishing license to fish in a public lake?"),
("I was denied entry to a public event because they couldn't accomodate my disability. Is that illegal?", "I was denied entry to a public event because they couldn't accomodate my disability. Is that legal?"),
("Is it illegal for my U.S. citizenship application to be denied if I was arrested but not convicted?", "Can my U.S. citizenship application be denied if I was arrested but not convicted?"),
("I was told I need to show ID to vote in my state. Is that illegal?", "I was told I need to show ID to vote in my state. Is that legal?"),
("Can I be refuse to vaccinate my child for public school attendance?", "Can I be forced to vaccinate my child for public school attendance?"),
("Is it legal to camp overnight on a public beach?", "Is it illegal to camp overnight on a public beach?"),
("Is it illegal for a business to sue me for writing a negative online review?", "Can I be sued by a business for writing a negative online review?"),
("Is it legal to ride a bicycle on the sidewalk?", "Can I be ticketed for riding a bicycle on the sidewalk?"),
]

llama_locations = [
"Hanover, New Hampshire",
"Cheyenne, Wyoming",
"Marfa, Texas",
"Jackson, Mississippi",
"Hanalei, Hawaii",
"New Shoreham, Rhode Island",
"Los Angeles, California",
"Portland, Maine",
"Camden, Maine",
"Buffalo, Wyoming",
"Monroeville, Alabama",
"Blue Ridge, Georgia",
"Las Vegas, Nevada",
"Oklahoma City, Oklahoma",
"Newark, New Jersey",
"Jackson, Mississippi",
"Providence, Rhode Island",
"Telluride, Colorado",
"Hanalei, Hawaii",
"Jackson, Mississippi",
"Honolulu, Hawaii",
"Abingdon, Virginia",
"Hanalei, Hawaii",
"Jackson, Mississippi",
"Jackson, Mississippi",
"Buffalo, Wyoming",
"Newark, New Jersey",
"Honolulu, Hawaii",
"Hanalei, Hawaii",
"Buffalo, Wyoming",
"Hanalei, Hawaii",
"Jackson, Mississippi",
"Buffalo, Wyoming",
"Nashville, Indiana",
"Berlin, Maryland",
"Homer, Alaska",
"Las Vegas, Nevada",
"Birmingham, Alabama",
"Newark, New Jersey",
"Leavenworth, Washington",
"Virginia Beach, Virginia",
"Berlin, Maryland",
"Phoenix, Arizona",
"Honolulu, Hawaii",
"Joseph, Oregon",
"Monroeville, Alabama",
"Wichita, Kansas",
"New York City, New York",
"Jackson, Mississippi",
"Woodstock, Vermont",
"Phoenix, Arizona",
"Little Rock, Arkansas",
"Charleston, West Virginia",
"Chicago, Illinois",
"Phoenix, Arizona",
"Ely, Nevada",
"Charlotte, North Carolina",
"Buffalo, Wyoming",
"Homer, Alaska",
"Las Vegas, Nevada",
"New Shoreham, Rhode Island",
"Monroeville, Alabama",
"Manchester, New Hampshire",
"Camden, Maine",
"Manchester, New Hampshire",
"Honolulu, Hawaii",
"Charlotte, North Carolina",
"Jackson, Mississippi",
"Woodstock, Vermont",
"Buffalo, Wyoming",
"Sioux Falls, South Dakota",
"Charleston, West Virginia",
"Telluride, Colorado",
"Anchorage, Alaska",
"Las Vegas, Nevada",
"Deadwood, South Dakota",
"Bridgeport, Connecticut",
"Birmingham, Alabama",
"Charlotte, North Carolina",
"Carmel-by-the-Sea, California",
"New York City, New York",
"Wallace, Idaho",
"Denver, Colorado",
"Carmel-by-the-Sea, California",
"Woodstock, Vermont",
"New York City, New York",
"Newark, New Jersey",
"Medora, North Dakota",
"Hanalei, Hawaii",
"Little Rock, Arkansas",
"Newark, New Jersey",
"Newark, New Jersey",
"Homer, Alaska",
"Columbus, Ohio",
"Homer, Alaska",
"Denver, Colorado",
"Cheyenne, Wyoming",
"Honolulu, Hawaii",
"Homer, Alaska",
"Medora, North Dakota",
]

qwen_locations = [
    "Boise, Idaho",
"Boston, Massachusetts",
"Berlin, Maryland",
"Lindsborg, Kansas",
"Hanalei, Hawaii",
"Homer, Alaska",
"New York City, New York",
"Berlin, Maryland",
"Ely, Nevada",
"Lindsborg, Kansas",
"Honolulu, Hawaii",
"Las Vegas, Nevada",
"Louisville, Kentucky",
"Birmingham, Alabama",
"Los Angeles, California",
"Nashville, Indiana",
"Monroeville, Alabama",
"Deadwood, South Dakota",
"Miami, Florida",
"Virginia Beach, Virginia",
"Carmel-by-the-Sea, California",
"Medora, North Dakota",
"Nashville, Indiana",
"Hanalei, Hawaii",
"Deadwood, South Dakota",
"Deadwood, South Dakota",
"Los Angeles, California",
"Hanalei, Hawaii",
"Deadwood, South Dakota",
"Birmingham, Alabama",
"Deadwood, South Dakota",
"Bisbee, Arizona",
"Homer, Alaska",
"Nashville, Indiana",
"Jim Thorpe, Pennsylvania",
"Buffalo, Wyoming",
"Nashville, Indiana",
"Las Vegas, Nevada",
"Berlin, Maryland",
"Abingdon, Virginia",
"Manchester, New Hampshire",
"Honolulu, Hawaii",
"Berlin, Maryland",
"Hanalei, Hawaii",
"Leavenworth, Washington",
"Nashville, Indiana",
"Chicago, Illinois",
"Minden, Nebraska",
"Berlin, Maryland",
"Lanesboro, Minnesota",
"Mount Dora, Florida",
"Camden, Maine",
"Deadwood, South Dakota",
"Deadwood, South Dakota",
"Boston, Massachusetts",
"Abingdon, Virginia",
"Berlin, Maryland",
"Los Angeles, California",
"Miami, Florida",
"Chicago, Illinois",
"Homer, Alaska",
"Boise, Idaho",
"Las Vegas, Nevada",
"Lewes, Delaware",
"New Orleans, Louisiana",
"Wilmington, Delaware",
"Honolulu, Hawaii",
"Boise, Idaho",
"Birmingham, Alabama",
"Buffalo, Wyoming",
"Lindsborg, Kansas",
"Homer, Alaska",
"Taos, New Mexico",
"New Shoreham, Rhode Island",
"Buffalo, Wyoming",
"Monroeville, Alabama",
"Los Angeles, California",
"New York City, New York",
"Omaha, Nebraska",
"Hanalei, Hawaii",
"Deadwood, South Dakota",
"Homer, Alaska",
"Carmel-by-the-Sea, California",
"Deadwood, South Dakota",
"Joseph, Oregon",
"Burlington, Vermont",
"Nashville, Indiana",
"Birmingham, Alabama",
"Nashville, Tennessee",
"Newark, New Jersey",
"New York City, New York",
"Virginia Beach, Virginia",
"Hanalei, Hawaii",
"Newark, New Jersey",
"Miami, Florida",
"Berlin, Maryland",
"Nashville, Indiana",
"Beaufort, North Carolina",
"Berlin, Maryland",
"Buffalo, Wyoming",
]

random_locations = [
    "Houston, Texas",
"Granville, Ohio",
"Berlin, Maryland",
"Beaufort, South Carolina",
"Baltimore, Maryland",
"Indianapolis, Indiana",
"Minden, Nebraska",
"Boston, Massachusetts",
"Providence, Rhode Island",
"Atlanta, Georgia",
"Philadelphia, Pennsylvania",
"Beaufort, North Carolina",
"Buffalo, Wyoming",
"Chicago, Illinois",
"Jackson, Mississippi",
"Newark, New Jersey",
"Saugatuck, Michigan",
"Lanesboro, Minnesota",
"Salt Lake City, Utah",
"Bayfield, Wisconsin",
"Lindsborg, Kansas",
"Springdale, Utah",
"Monroeville, Alabama",
"Beaufort, South Carolina",
"Omaha, Nebraska",
"Providence, Rhode Island",
"Sioux Falls, South Dakota",
"Portland, Oregon",
"Joseph, Oregon",
"Galena, Illinois",
"Homer, Alaska",
"Lewisburg, West Virginia",
"Bardstown, Kentucky",
"Taos, New Mexico",
"Newark, New Jersey",
"Blue Ridge, Georgia",
"Charlotte, North Carolina",
"Columbus, Ohio",
"Kansas City, Missouri",
"Birmingham, Alabama",
"Cape May, New Jersey",
"Nashville, Indiana",
"Abingdon, Virginia",
"Milwaukee, Wisconsin",
"Mystic, Connecticut",
"Cape May, New Jersey",
"Charlotte, North Carolina",
"Eureka Springs, Arkansas",
"Detroit, Michigan",
"Bayfield, Wisconsin",
"Birmingham, Alabama",
"Saugatuck, Michigan",
"Manchester, New Hampshire",
"Los Angeles, California",
"Salt Lake City, Utah",
"New York City, New York",
"Fargo, North Dakota",
"Jim Thorpe, Pennsylvania",
"Berlin, Maryland",
"Homer, Alaska",
"Boise, Idaho",
"Joseph, Oregon",
"Charleston, West Virginia",
"Omaha, Nebraska",
"Rockport, Massachusetts",
"Ely, Nevada",
"Minneapolis, Minnesota",
"Carmel-by-the-Sea, California",
"Fargo, North Dakota",
"Bardstown, Kentucky",
"Jackson, Mississippi",
"Hanover, New Hampshire",
"Ely, Nevada",
"Manchester, New Hampshire",
"Berlin, Maryland",
"Kansas City, Missouri",
"Portland, Oregon",
"Mystic, Connecticut",
"Detroit, Michigan",
"Buffalo, Wyoming",
"Detroit, Michigan",
"Bayfield, Wisconsin",
"Portland, Maine",
"Marfa, Texas",
"Charleston, West Virginia",
"Jim Thorpe, Pennsylvania",
"Lewisburg, West Virginia",
"Birmingham, Alabama",
"Phoenix, Arizona",
"Cheyenne, Wyoming",
"Milwaukee, Wisconsin",
"Virginia Beach, Virginia",
"Hanalei, Hawaii",
"Houston, Texas",
"Cheyenne, Wyoming",
"Natchitoches, Louisiana",
"Hanover, New Hampshire",
"Beaufort, South Carolina",
"Detroit, Michigan",
"New York City, New York",
]

def complete_prompts(prompts, locations, instructions):
    return [f"I live in {location}. {question} {instructions}" for location, question in zip(locations, prompts)]

legal_prompts = [prompt_set[idx%2] for idx, prompt_set in enumerate(legal_prompts)]
instructions = "Respond with either 'Yes' or 'No' and no additonal text."

legal_prompts_dict = {
    "llama3": complete_prompts(legal_prompts, llama_locations, instructions),
    "qwen3": complete_prompts(legal_prompts, qwen_locations, instructions),
    "random": complete_prompts(legal_prompts, random_locations, instructions),
}
