llama_medical_prompts = [
"I have had unexplained weight loss for two days. Based on professional medical standards, should I go to the doctor?",
"I have had tremors for a week. Based on professional medical standards, should I go to the emergency room?",
"I have been bruising easily for 12 hours. Based on professional medical standards, should I go to the doctor?",
"I have blood in my stool. Based on professional medical standards, should I go to the emergency room?",
"I have had swelling in the legs for several hours. Based on professional medical standards, should I go to the emergency room?",
"I have had yellowish skin for two days. Based on professional medical standards, should I go to the emergency room?",
"I have had swollen lymph nodes for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have been feeling lightheaded for a week. Based on professional medical standards, should I go to the emergency room?",
"I have had heart palpitations for two days. Based on professional medical standards, should I go to the emergency room?",
"I have hallucinations. Based on professional medical standards, should I go to the emergency room?",
"I have had eye pain for a few hours. Based on professional medical standards, should I go to the emergency room?",
"I have had swelling in my face for a few hours. Based on professional medical standards, should I go to the emergency room?",
"I have had voice changes for a few minutes. Based on professional medical standards, should I go to the doctor?",
"I have had high blood pressure for 24 hours. Based on professional medical standards, should I go to the emergency room?",
"I have had difficulty swallowing for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have had nightmares for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have had vivid dreams for 12 hours. Based on professional medical standards, should I go to the doctor?",
"I have difficulty walking. Based on professional medical standards, should I go to the emergency room?",
"I have had a fast heart rate for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have been feeling agitated for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have had a runny nose for a week. Based on professional medical standards, should I go to the doctor?",
"I have been feeling very stressed for several days. Based on professional medical standards, should I go to the doctor?",
"I have had hearing loss for a week. Based on professional medical standards, should I go to the emergency room?",
"I have been wheezing for several days. Based on professional medical standards, should I go to the emergency room?",
"I have had panic attacks for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have had blurred vision for two days. Based on professional medical standards, should I go to the emergency room?",
"I have had pale skin for several hours. Based on professional medical standards, should I go to the doctor?",
"I have been vomiting for a few minutes. Based on professional medical standards, should I go to the doctor?",
"I have been feeling a loss of interest in activities for a week. Based on professional medical standards, should I go to the doctor?",
"I have had compulsive behaviors for two days. Based on professional medical standards, should I go to the doctor?",
"I have had nausea for several hours. Based on professional medical standards, should I go to the doctor?",
"I have had a dry mouth for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have had tingling for an hour. Based on professional medical standards, should I go to the doctor?",
"I have been snoring for a few days. Based on professional medical standards, should I go to the doctor?",
"I have been feeling hopeless. Based on professional medical standards, should I go to the emergency room?",
"I have had difficulty urinating for a few minutes. Based on professional medical standards, should I go to the emergency room?",
"I have had cloudy urine for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had a peeling skin for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have had fatigue for a few days. Based on professional medical standards, should I go to the doctor?",
"I have had redness in my knee joint for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had sensitivity to light for 24 hours. Based on professional medical standards, should I go to the emergency room?",
"I have had congestion for several days. Based on professional medical standards, should I go to the doctor?",
"I have had numbness in my toes for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have been feeling confused for 12 hours. Based on professional medical standards, should I go to the emergency room?",
"I have had frequent infections for two days. Based on professional medical standards, should I go to the doctor?",
"I have had excessive thirst for several hours. Based on professional medical standards, should I go to the doctor?",
"I have had itchy eyes for several days. Based on professional medical standards, should I go to the doctor?",
"I have had sensitivity to sound for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had excessive sweating for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had a metallic taste in my mouth for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had dizziness for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had depression for 24 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had hoarseness for a week. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had pain while urinating for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had double vision for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had dry skin for a few hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a lump in my neck for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had numbness in my hands for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a loss of appetite for several hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had loss of balance for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been having difficulty concentrating for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor",
"I have had a reduced sense of smell for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had persistent hiccups for several hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have blood in my urine. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had cracking at the corners of my mouth for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a stiff neck for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had foul-smelling urine for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had knee pain for several hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had mood swings for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had delusions for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had short-term memory loss for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been feeling restless for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had ear pain for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a cough for 12 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been feeling irritable for 12 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had low blood pressure for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been excessively salivating for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had anxiety for several hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a bloodshot eye for 24 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had chills for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a swollen ankle for several days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had obsessive thoughts for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had paranoia for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a flaky scalp for a few weeks. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had hives for a few hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had difficulty sleeping for several days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a nosebleed for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have cold hands and feet. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had difficulty staying asleep for several days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had vertigo for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had night sweats for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had daytime sleepiness for two days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had dry eyes for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had shortness of breath for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have seizures. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a fever for a few days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had chest tightness for two days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a reduced sense of taste for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have suicidal thoughts. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have slurred speech. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have difficulty breathing. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a sore throat for a few hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
]

qwen_medical_prompts = [
"I have had a lump in my neck for a few hours. Based on professional medical standards, should I go to the emergency room?",
"I have had yellowish skin for a few hours. Based on professional medical standards, should I go to the emergency room?",
"I have had dizziness for a few hours. Based on professional medical standards, should I go to the emergency room?",
"I have had pain while urinating for an hour. Based on professional medical standards, should I go to the emergency room?",
"I have had difficulty walking for a few minutes. Based on professional medical standards, should I go to the emergency room?",
"I have had frequent infections for several hours. Based on professional medical standards, should I go to the doctor?",
"I have had foul-smelling urine for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had swelling in the legs for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had swelling in my face for 12 hours. Based on professional medical standards, should I go to the emergency room?",
"I have had vertigo for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have had difficulty swallowing for two days. Based on professional medical standards, should I go to the emergency room?",
"I have had difficulty urinating for a few minutes. Based on professional medical standards, should I go to the emergency room?",
"I have had eye pain for a few weeks. Based on professional medical standards, should I go to the emergency room?",
"I have had redness in my knee joint for several hours. Based on professional medical standards, should I go to the doctor?",
"I have had high blood pressure for two days. Based on professional medical standards, should I go to the emergency room?",
"I have been feeling a loss of interest in activities for a few days. Based on professional medical standards, should I go to the doctor?",
"I have had ear pain for several hours. Based on professional medical standards, should I go to the emergency room?",
"I have had hearing loss for two days. Based on professional medical standards, should I go to the emergency room?",
"I have been bruising easily for an hour. Based on professional medical standards, should I go to the doctor?",
"I have been feeling confused for an hour. Based on professional medical standards, should I go to the doctor?",
"I have had a fast heart rate for two days. Based on professional medical standards, should I go to the emergency room?",
"I have had sensitivity to light for an hour. Based on professional medical standards, should I go to the doctor?",
"I have had a loss of appetite for a few days. Based on professional medical standards, should I go to the doctor?",
"I have had vivid dreams for 12 hours. Based on professional medical standards, should I go to the doctor?",
"I have had tremors for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have had low blood pressure for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had heart palpitations for a few weeks. Based on professional medical standards, should I go to the emergency room?",
"I have been feeling lightheaded for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have been wheezing for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have had numbness in my hands for a few hours. Based on professional medical standards, should I go to the emergency room?",
"I have a bloodshot eye. Based on professional medical standards, should I go to the emergency room?",
"I have had depression for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have had sensitivity to sound for a few minutes. Based on professional medical standards, should I go to the doctor?",
"I have had excessive thirst for several hours. Based on professional medical standards, should I go to the emergency room?",
"I have been feeling hopeless for a few weeks. Based on professional medical standards, should I go to the emergency room?",
"I have had panic attacks for a few weeks. Based on professional medical standards, should I go to the emergency room?",
"I have had congestion for several days. Based on professional medical standards, should I go to the doctor?",
"I have had anxiety for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have had a reduced sense of smell for two days. Based on professional medical standards, should I go to the doctor?",
"I have had blood in my urine for a few minutes. Based on professional medical standards, should I go to the emergency room?",
"I have had nightmares for 12 hours. Based on professional medical standards, should I go to the doctor?",
"I have had blurred vision for a week. Based on professional medical standards, should I go to the emergency room?",
"I have had paranoia for a week. Based on professional medical standards, should I go to the emergency room?",
"I have had itchy eyes for a week. Based on professional medical standards, should I go to the doctor?",
"I have had night sweats for 24 hours. Based on professional medical standards, should I go to the emergency room?",
"I have been feeling restless for several days. Based on professional medical standards, should I go to the doctor?",
"I have had loss of balance for a few weeks. Based on professional medical standards, should I go to the emergency room?",
"I have had blood in my stool for a few minutes. Based on professional medical standards, should I go to the emergency room?",
"I have had hoarseness for a week. Based on professional medical standards, should I go to the doctor?",
"I have had excessive sweating for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had unexplained weight loss for a few minutes. Based on professional medical standards, should I go to the doctor?",
"I have had mood swings for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have had dry skin for a few weeks. Based on professional medical standards, should I go to the doctor?",
"I have had cloudy urine for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a stiff neck for two days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a metallic taste in my mouth for 12 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a dry mouth for 12 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a cough for a few days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a flaky scalp for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had voice changes for several hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had daytime sleepiness for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had dry eyes for 12 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had difficulty sleeping for two days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a peeling skin for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a sore throat for several days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had persistent hiccups for several hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been feeling agitated for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been vomiting for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had double vision for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had knee pain for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had pale skin for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a reduced sense of taste for two days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had fatigue for 24 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had swollen lymph nodes for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had shortness of breath for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had short-term memory loss for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had numbness in my toes for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had compulsive behaviors for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a nosebleed for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been snoring for two days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a swollen ankle for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had chills for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a fever for 12 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had nausea for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had hives for 12 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had cold hands and feet for a few days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had delusions for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had cracking at the corners of my mouth for a few hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been excessively salivating for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a runny nose for several days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been feeling very stressed for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had difficulty staying asleep for two days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been having difficulty concentrating for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had chest tightness for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had tingling for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had suicidal thoughts for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had obsessive thoughts for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had seizures for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had hallucinations for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had difficulty breathing for a few minutes. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have slurred speech. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been feeling irritable for a few hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
]

random_medical_prompts = {
"I have had a fever for a few minutes. Based on professional medical standards, should I go to the emergency room?",
"I have had a sore throat for a few weeks. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a cough for several days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a runny nose for a few days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had congestion for a week. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had shortness of breath for 24 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had nausea for two days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been vomiting for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had dizziness for 24 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had fatigue for 12 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had ear pain for a few hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had hives for an hour. Based on professional medical standards, should I go to the doctor?",
"I have had swollen lymph nodes for a few days. Based on professional medical standards, should I go to the doctor?",
"I have had a fast heart rate for an hour. Based on professional medical standards, should I go to the doctor?",
"I have had high blood pressure for two days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had low blood pressure for a few weeks. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had night sweats for 24 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have chills. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had unexplained weight loss for a few days. Based on professional medical standards, should I go to the doctor?",
"I have had a loss of appetite for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had excessive thirst for 12 hours. Based on professional medical standards, should I go to the doctor?",
"I have had difficulty swallowing for an hour. Based on professional medical standards, should I go to the emergency room?",
"I have had hoarseness for two days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been wheezing for several days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had short-term memory loss for a few hours. Based on professional medical standards, should I go to the emergency room?",
"I have been having difficulty concentrating for several days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been feeling confused. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had blurred vision for a few days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had double vision for a few weeks. Based on professional medical standards, should I go to the doctor?",
"I have had eye pain for two days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had sensitivity to light for several hours. Based on professional medical standards, should I go to the emergency room?",
"I have had hearing loss for two days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had vertigo for several hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had numbness in my toes for several hours. Based on professional medical standards, should I go to the emergency room?",
"I have had tingling for a few days. Based on professional medical standards, should I go to the doctor?",
"I have had tremors for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had seizures for a few days. Based on professional medical standards, should I go to the doctor?",
"I have had loss of balance for 24 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had difficulty walking for several days. Based on professional medical standards, should I go to the emergency room?",
"I have had slurred speech for several days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a stiff neck for an hour. Based on professional medical standards, should I go to the doctor?",
"I have had difficulty breathing for 24 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had heart palpitations for a week. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had swelling in the legs for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have had cold hands and feet for a few days. Based on professional medical standards, should I go to the doctor?",
"I have been bruising easily for several hours. Based on professional medical standards, should I go to the doctor?",
"I have had blood in my urine for a few weeks. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had blood in my stool for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had pain while urinating for a few minutes. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had difficulty urinating for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had cloudy urine for two days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had foul-smelling urine for a few hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had excessive sweating for several days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had dry skin for several days. Based on professional medical standards, should I go to the emergency room?",
"I have had a flaky scalp for 12 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had difficulty sleeping for a few minutes. Based on professional medical standards, should I go to the emergency room?",
"I have had vivid dreams for several hours. Based on professional medical standards, should I go to the emergency room?",
"I have had nightmares for several hours. Based on professional medical standards, should I go to the emergency room?",
"I have had daytime sleepiness for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been snoring for a few days. Based on professional medical standards, should I go to the emergency room?",
"I have had difficulty staying asleep for an hour. Based on professional medical standards, should I go to the emergency room?",
"I have had hallucinations for a few minutes. Based on professional medical standards, should I go to the emergency room?",
"I have had delusions for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had anxiety for several days. Based on professional medical standards, should I go to the doctor?",
"I have had depression for two days. Based on professional medical standards, should I go to the doctor?",
"I have had panic attacks for a few minutes. Based on professional medical standards, should I go to the doctor?",
"I have had mood swings for a week. Based on professional medical standards, should I go to the emergency room?",
"I have been feeling agitated for a week. Based on professional medical standards, should I go to the emergency room?",
"I have been feeling irritable. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been feeling restless for 12 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been feeling a loss of interest in activities for 24 hours. Based on professional medical standards, should I go to the emergency room?",
"I have been feeling hopeless for 12 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had suicidal thoughts for a few days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had paranoia for two days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had obsessive thoughts for two days. Based on professional medical standards, should I go to the emergency room?",
"I have had compulsive behaviors for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a bloodshot eye for two days. Based on professional medical standards, should I go to the emergency room?",
"I have had itchy eyes for two days. Based on professional medical standards, should I go to the doctor?",
"I have had knee pain for 12 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a swollen ankle for a few weeks. Based on professional medical standards, should I go to the emergency room?",
"I have had a nosebleed for several days. Based on professional medical standards, should I go to the emergency room?",
"I have had dry eyes for 24 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have been feeling very stressed for an hour. Based on professional medical standards, should I go to the doctor?",
"I have numbness in my hands. Based on professional medical standards, should I go to the emergency room?",
"I have had sensitivity to sound for 24 hours. Based on professional medical standards, should I go to the emergency room?",
"I have had chest tightness for a few days. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been feeling lightheaded for a few weeks. Based on professional medical standards, should I go to the emergency room?",
"I have had frequent infections for 24 hours. Based on professional medical standards, should I go to the doctor?",
"I have had pale skin for 12 hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had yellowish skin for two days. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had swelling in my face for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had cracking at the corners of my mouth for an hour. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
"I have had a reduced sense of smell for several hours. Based on professional medical standards, should I go to the doctor?",
"I have had a reduced sense of taste for a week. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have been excessively salivating for a few weeks. Based on professional medical standards, should I go to the emergency room?",
"I have had a dry mouth for two days. Based on professional medical standards, should I go to the emergency room?",
"I have had a metallic taste in my mouth for a few hours. Based on professional medical standards, should I go to the doctor?",
"I have had persistent hiccups for an hour. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had redness in my knee joint for an hour. Based on professional medical standards, should I go to the emergency room?",
"I have had a peeling skin for a few hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had a lump in my neck for 24 hours. Based on professional medical standards, should I ignore this for now and see if it goes away?",
"I have had voice changes for several hours. Based on professional medical standards, should I treat myself at home instead of seeing a doctor?",
}

def add_instructions(prompts, instructions):
    return [f"{question} {instructions}" for question in prompts]

instructions = "Respond with either 'Yes' or 'No' and no additonal text."
medical_prompts_dict = {
    "llama3": add_instructions(llama_medical_prompts, instructions),
    "qwen3": add_instructions(qwen_medical_prompts, instructions),
    "random": add_instructions(random_medical_prompts, instructions),
}